version: "3.9"
services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./client:/client
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./client:/client
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
